#!/bin/bash
# Apex Server — generic launcher
# Usage: bash server/launch.sh
#
# Configuration: Set env vars in ~/.apex/.env or export them before running.
# Required: APEX_SSL_CERT, APEX_SSL_KEY, APEX_SSL_CA (run setup.py first)
# Optional: APEX_MODEL, APEX_WORKSPACE, APEX_PORT, APEX_DEBUG, etc.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APEX_ROOT="$(dirname "$SCRIPT_DIR")"

# Load user .env (check multiple standard locations)
# Load credentials (all found .env files — later ones override earlier)
if [ -n "${APEX_ENV_FILE:-}" ] && [ -f "$APEX_ENV_FILE" ]; then
    set -a; source "$APEX_ENV_FILE"; set +a
    echo "Loaded env from: $APEX_ENV_FILE"
else
    for candidate in "$HOME/.apex/.env" "$HOME/.config/apex/.env" "$APEX_ROOT/.env"; do
        if [ -f "$candidate" ]; then
            set -a; source "$candidate"; set +a
            echo "Loaded env from: $candidate"
        fi
    done
fi

# SSL cert defaults (generated by setup.py)
SSL_DIR="$APEX_ROOT/state/ssl"
export APEX_SSL_CERT="${APEX_SSL_CERT:-$SSL_DIR/apex.crt}"
export APEX_SSL_KEY="${APEX_SSL_KEY:-$SSL_DIR/apex.key}"
export APEX_SSL_CA="${APEX_SSL_CA:-$SSL_DIR/ca.crt}"
export APEX_ROOT="$APEX_ROOT"

# First-run detection
if [ ! -f "$APEX_SSL_CA" ]; then
    echo "SSL certificates not found. Run setup first:"
    echo "  python3 $APEX_ROOT/setup.py"
    exit 1
fi

# Optional: backup DB before starting
if [ -x "$SCRIPT_DIR/backup_db.sh" ]; then
    bash "$SCRIPT_DIR/backup_db.sh" 2>/dev/null || true
fi

echo "=== Apex Server ==="
echo "  Root:  $APEX_ROOT"
echo "  Port:  ${APEX_PORT:-8300}"
echo "  Model: ${APEX_MODEL:-claude-sonnet-4-6}"
echo "==================="

cd "$APEX_ROOT"

# Use venv Python if available (created by setup.py)
PYTHON="$APEX_ROOT/.venv/bin/python3"
if [ ! -x "$PYTHON" ]; then
    PYTHON="python3"
fi

exec "$PYTHON" "$SCRIPT_DIR/apex.py"
